import type { CauseOfDeath, DeadStablecoin } from "./types";

export const CAUSE_META: Record<CauseOfDeath, { label: string; color: string }> = {
  "algorithmic-failure": { label: "Algorithmic Failure", color: "text-red-500 border-red-500/30" },
  "counterparty-failure": { label: "Counterparty Failure", color: "text-amber-500 border-amber-500/30" },
  "liquidity-drain": { label: "Liquidity Drain", color: "text-orange-500 border-orange-500/30" },
  "regulatory": { label: "Regulatory", color: "text-blue-500 border-blue-500/30" },
  "abandoned": { label: "Abandoned", color: "text-zinc-500 border-zinc-500/30" },
};

/**
 * Dead stablecoins, sorted chronologically (oldest death first).
 * peakMcap values from DefiLlama historical data where available.
 * logo is a filename under /logos/cemetery/ (downloaded from CoinGecko).
 */
export const DEAD_STABLECOINS: DeadStablecoin[] = [
  // ── 2018 ────────────────────────────────────────────────────────────
  {
    name: "NuBits",
    symbol: "USNBT",
    logo: "nubits.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2018-03",
    obituary:
      "One of the first stablecoins ever created (2014), NuBits held its peg for two years before collapsing when holders dumped it to chase Bitcoin gains. A pioneering cautionary tale about algorithmic pegs backed by volatile assets. (Excluded from timeline view due to early date.)",
    sourceUrl: "https://medium.com/reserve-currency/the-end-of-a-stablecoin-the-case-of-nubits-dd1f0fb427a9",
    sourceLabel: "Reserve Research",
  },

  // ── 2021 ────────────────────────────────────────────────────────────
  {
    name: "Empty Set Dollar",
    symbol: "ESD",
    logo: "esd.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2021-01",
    peakMcap: 550_000_000,
    obituary:
      "Pioneered the \"seigniorage shares\" model in DeFi. When ESD traded below $1, users could buy coupons (burning ESD) in hopes of future redemption at a profit. The mechanism worked during expansion but collapsed when confidence evaporated — coupons expired worthless, and ESD fell to $0.01.",
    sourceUrl: "https://thedailyeconomy.org/article/algorithmic-stablecoins/",
    sourceLabel: "The Daily Economy",
  },
  {
    name: "Dynamic Set Dollar",
    symbol: "DSD",
    logo: "dsd.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2021-01",
    peakMcap: 300_000_000,
    obituary:
      "A fork of ESD with faster epoch cycles (2 hours vs 8 hours), designed to stabilize more quickly. Instead, the shorter cycles amplified volatility. DSD spiked to $3 during expansion then collapsed to $0.24 in the same month, proving that faster reflexivity cuts both ways.",
    sourceUrl: "https://cointelegraph.com/news/dynamic-set-dollar-faces-massive-test-as-stablecoin-falls-as-low-as-27",
    sourceLabel: "CoinTelegraph",
  },
  {
    name: "Basis Cash",
    symbol: "BAC",
    logo: "bac.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2021-01",
    obituary:
      "An anonymous fork of the Basis design, BAC lost its peg within weeks of launch. Later revealed to be co-founded by Do Kwon under a pseudonym -- who learned nothing before building the even more catastrophic TerraUSD.",
    sourceUrl: "https://protos.com/basis-cash-the-failed-algorithmic-stablecoin-do-kwon-didnt-learn-from",
    sourceLabel: "Protos",
  },
  {
    name: "IRON",
    symbol: "IRON",
    logo: "iron.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2021-06",
    obituary:
      "Dubbed crypto's \"first large-scale bank run.\" IRON was partially collateralized (75% USDC, 25% TITAN token). When whales dumped TITAN at its peak, a flawed redemption mechanism sent TITAN from $65 to zero in hours, dragging IRON down with it.",
    sourceUrl: "https://www.coindesk.com/markets/2021/06/17/in-token-crash-postmortem-iron-finance-says-it-suffered-cryptos-first-large-scale-bank-run",
    sourceLabel: "CoinDesk",
  },

  {
    name: "Vai",
    symbol: "VAI",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2021-09",
    peakMcap: 318_800_000,
    obituary:
      "Venus Protocol's synthetic stablecoin on BSC was minted freely during DeFi summer 2021 — too freely. A $77M bad-debt crisis cratered confidence, VAI shed its peg to $0.74, and minting was paused. Supply collapsed 99% from $300M+ to under $3M.",
    sourceUrl: "https://cointelegraph.com/news/these-are-the-least-stable-stablecoins-not-named-terrausd",
    sourceLabel: "CoinTelegraph",
  },

  // ── 2022 ────────────────────────────────────────────────────────────
  {
    name: "Neutrino USD",
    symbol: "USDN",
    logo: "usdn.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2022-04",
    peakMcap: 1_023_616_756,
    obituary:
      "Succumbed to an algorithmic death spiral after WAVES price manipulation destabilized collateral backing. Rebranded to XTN, now trading at $0.02.",
    sourceUrl: "https://cointelegraph.com/news/neutrino-dollar-breaks-peg-falls-to-0-82-amid-waves-price-manipulation-accusations",
    sourceLabel: "CoinTelegraph",
  },
  {
    name: "TerraUSD",
    symbol: "UST",
    logo: "ust.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2022-05",
    peakMcap: 18_770_471_902,
    obituary:
      "The largest stablecoin collapse in history. UST's algorithmic peg relied on minting/burning LUNA, but a coordinated sell-off triggered a death spiral that vaporized $40B in combined value within days. Anchor's unsustainable 20% yield had concentrated 70% of supply in a single venue.",
    sourceUrl: "https://www.coindesk.com/tech/2022/05/11/usts-do-kwon-was-behind-earlier-failed-stablecoin-ex-terra-colleagues-say",
    sourceLabel: "CoinDesk",
  },
  {
    name: "DEI",
    symbol: "DEI",
    logo: "dei.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2022-05",
    obituary:
      "An algorithmic stablecoin on Fantom hit by flash loan exploits totaling $16M, then finished off by contagion from UST's collapse. A further hack in May 2023 delivered the final blow.",
    sourceUrl: "https://www.coindesk.com/markets/2022/05/16/fantom-stablecoin-dei-becomes-latest-to-lose-dollar-peg",
    sourceLabel: "CoinDesk",
  },
  {
    name: "flexUSD",
    symbol: "FLEXUSD",
    pegCurrency: "USD",
    causeOfDeath: "counterparty-failure",
    deathDate: "2022-06",
    peakMcap: 196_400_000,
    obituary:
      "CoinFLEX's interest-bearing stablecoin promised yields up to 114% APY from its futures lending market. When Roger Ver's account blew an $84M hole in the exchange, flexUSD holders discovered 'interest-bearing' also meant 'loss-bearing.' The exchange froze all redemptions, rebranded into OPNX with Three Arrows Capital's founders, and that venture also collapsed. 166M flexUSD tokens sit unredeemable at $0.08.",
    sourceUrl: "https://techstory.in/coinflexs-flexusd-is-the-new-entrant-in-the-club-of-failed-stablecoins/",
    sourceLabel: "TechStory",
  },
  {
    name: "VOLT Protocol",
    symbol: "VOLT",
    pegCurrency: "VAR",
    causeOfDeath: "counterparty-failure",
    deathDate: "2022-08",
    peakMcap: 20_100_000,
    obituary:
      "The first CPI-pegged stablecoin promised inflation protection via yields from Rari Fuse lending markets. When the $80M Fuse exploit wiped out those markets, VOLT lost its yield engine. The Tribe DAO dissolution four months later removed the last collateral backstop; the team pivoted to Ethereum Credit Guild.",
    sourceUrl: "https://decrypt.co/97365/volt-protocol-raises-2-million-inflation-resistant-stablecoin",
    sourceLabel: "Decrypt",
  },
  {
    name: "Fei USD",
    symbol: "FEI",
    logo: "fei.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2022-08",
    peakMcap: 2_336_281_370,
    obituary:
      "Raised $1.3B in ETH at launch, but Tribe DAO voted to wind down citing mounting technical, financial, and regulatory risks. An $80M hack of merged Rari/Fuse lending markets sealed its fate. Holders redeemed 1:1 for DAI.",
    sourceUrl: "https://www.axios.com/2022/08/25/algorithmic-stablecoin-tribedao-fei",
    sourceLabel: "Axios",
  },
  {
    name: "HUSD",
    symbol: "HUSD",
    logo: "husd.jpg",
    pegCurrency: "USD",
    causeOfDeath: "counterparty-failure",
    deathDate: "2022-10",
    peakMcap: 393_463_176,
    obituary:
      "A fiat-backed stablecoin tied to the Huobi ecosystem. When Justin Sun acquired Huobi and replaced it with USDD, HUSD was delisted with no redemption path. Crashed to $0.28.",
    sourceUrl: "https://www.coindesk.com/business/2022/10/31/after-huobi-delisting-stablecoin-husd-falls-72-from-dollar-peg",
    sourceLabel: "CoinDesk",
  },

  // ── 2023 ────────────────────────────────────────────────────────────
  {
    name: "Sperax USD",
    symbol: "USDs",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2023-02",
    peakMcap: 25_100_000,
    obituary:
      "Sperax promised auto-yield just from holding its stablecoin on Arbitrum — no staking required. Then a rebasing bug let someone mint 9.7 billion tokens out of thin air. The funds came back, but user trust didn't. Backed by Alameda at peak hubris, USDs survived its exploit only to bleed out slowly.",
    sourceUrl: "https://crypto.news/sperax-usd-stablecoin-reportedly-hacked-for-250000/",
    sourceLabel: "Crypto News",
  },
  {
    name: "Binance USD",
    symbol: "BUSD",
    logo: "busd.jpg",
    pegCurrency: "USD",
    causeOfDeath: "regulatory",
    deathDate: "2023-02",
    peakMcap: 23_462_869_722,
    obituary:
      "Once the third-largest stablecoin at $23.5B. The NYDFS ordered issuer Paxos to stop minting, while the SEC signaled intent to sue. Binance ceased support in Dec 2023, auto-converting remaining balances to FDUSD.",
    sourceUrl: "https://www.coindesk.com/business/2023/02/13/paxos-to-stop-minting-stablecoin-busd-following-regulatory-action",
    sourceLabel: "CoinDesk",
  },
  {
    name: "Reserve",
    symbol: "RSV",
    logo: "rsv.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2023-03",
    peakMcap: 29_016_644,
    obituary:
      "Reserve's prototype stablecoin was deprecated when the protocol launched its RToken system. eUSD (Electronic Dollar) replaced RSV in the LATAM-focused Reserve app.",
    sourceUrl: "https://fortune.com/crypto/2023/07/03/sam-altman-stablecoin-reserve-venezuela-ofac/",
    sourceLabel: "Fortune Crypto",
  },
  {
    name: "mStable USD",
    symbol: "MUSD",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2023-04",
    peakMcap: 171_000_000,
    obituary:
      "mStable dreamed of unifying the fragmented stablecoin landscape — one meta-stablecoin to swap them all, with built-in yield. It touched $171M, but frictionless stablecoin swaps couldn't compete with DEX aggregators and simple USDC. When the co-founder walked away in early 2023, the DAO chose an honorable death: acquisition by dHedge.",
    sourceUrl: "https://www.coindesk.com/business/2023/03/15/defi-exchange-mstable-mulls-over-acquisition-merger-offers",
    sourceLabel: "CoinDesk",
  },
  {
    name: "USDK",
    symbol: "USDK",
    pegCurrency: "USD",
    causeOfDeath: "counterparty-failure",
    deathDate: "2023-06",
    peakMcap: 42_500_000,
    obituary:
      "USDK did everything right on paper: regulated US trust company, ERC-20 standard, clean audits. But its custodian Prime Trust was secretly gambling client funds on algorithmic stablecoins. When Prime Trust collapsed into receivership — revealed to be $82M short on customer fiat — USDK's 'fully backed' promise became just another line in a bankruptcy filing.",
    sourceUrl: "https://www.coindesk.com/policy/2023/06/27/nevada-places-crypto-custodian-prime-trust-into-receivership",
    sourceLabel: "CoinDesk",
  },
  {
    name: "USDP Stablecoin",
    symbol: "USDP",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2023-06",
    peakMcap: 279_700_000,
    obituary:
      "Unit Protocol's USDP accepted everything from Yearn vaults to SushiSwap LP tokens as collateral — a collateral buffet that attracted nearly $280M. But quantity of options couldn't substitute for quality of demand, and when Paxos swooped in with its own 'USDP' ticker, the identity crisis accelerated the decline. Supply withered to under $10K.",
    sourceUrl: "https://defillama.com/stablecoin/usdp-stablecoin",
    sourceLabel: "DefiLlama",
  },
  {
    name: "TOR",
    symbol: "TOR",
    logo: "tor.png",
    pegCurrency: "USD",
    causeOfDeath: "counterparty-failure",
    deathDate: "2023-07",
    peakMcap: 342_945_973,
    obituary:
      "Hector Network's stablecoin collapsed after the Multichain bridge exploit wiped out $8M of treasury assets. The DAO voted to liquidate the remaining $16M treasury, ending a project already plagued by allegations that the team squandered $100M+ in funds.",
    sourceUrl: "https://www.coindesk.com/business/2023/07/17/hector-network-votes-to-liquidate-16m-treasury-following-multichain-fantom-losses",
    sourceLabel: "CoinDesk",
  },
  {
    name: "Parrot USD",
    symbol: "PAI",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2023-07",
    peakMcap: 23_100_000,
    obituary:
      "Parrot Protocol raised $85M during Solana's DeFi summer, backed by Alameda Research. Two years and one FTX collapse later, the team held a governance vote to liquidate the $74M treasury and go tokenless. The vote passed 99.8% — allegedly stuffed with insider wallets — and IDO investors got back a dime on the dollar.",
    sourceUrl: "https://www.coindesk.com/markets/2023/07/21/defi-project-parrot-puts-fate-of-over-70m-treasury-prt-token-to-vote",
    sourceLabel: "CoinDesk",
  },
  {
    name: "Acala USD",
    symbol: "aUSD",
    logo: "ausd.png",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2023-07",
    peakMcap: 11_088_350,
    obituary:
      "Acala's aUSD lost its peg after a catastrophic exploit in August 2022 minted 1.28 billion unauthorized tokens. Converted to aSEED in July 2023, ceasing to function as a stablecoin.",
    sourceUrl: "https://www.coindesk.com/tech/2022/08/15/acalas-stablecoin-falls-99-percent-after-hackers-issue-13-billion-tokens/",
    sourceLabel: "CoinDesk",
  },
  {
    name: "Vesta Stable",
    symbol: "VST",
    logo: "vst.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2023-09",
    peakMcap: 32_044_597,
    obituary:
      "Vesta Finance dissolved after founders proposed to exit citing \"cultural differences.\" Community voted 96% for dissolution; VSTA holders received pro-rata treasury redemptions in USDC and ARB.",
    sourceUrl: "https://golden.com/wiki/Vesta_Finance-EKWBMZW",
    sourceLabel: "Golden",
  },
  {
    name: "Iron Bank EURO",
    symbol: "IBEUR",
    logo: "ibeur.png",
    pegCurrency: "EUR",
    causeOfDeath: "liquidity-drain",
    deathDate: "2023-12",
    peakMcap: 50_369_497,
    obituary:
      "Liquidity pools drained after Iron Bank's lending markets froze, leaving no clear path to repeg. Still trades at a fraction of face value.",
    sourceUrl: "https://www.coindesk.com/business/2023/12/19/crashed-stablecoin-iron-bank-euro-ibeur-lacks-clear-repeg-path",
    sourceLabel: "CoinDesk",
  },

  // ── 2024 ────────────────────────────────────────────────────────────
  {
    name: "Rai Reflex Index",
    symbol: "RAI",
    pegCurrency: "VAR",
    causeOfDeath: "abandoned",
    deathDate: "2024-02",
    peakMcap: 48_700_000,
    obituary:
      "The idealist's stablecoin: RAI rejected the dollar peg, embraced 'ungovernance,' and floated freely on pure math and ETH collateral. The team achieved their goal of removing all human governance, then did what the protocol couldn't: moved on to build HAI on Optimism.",
    sourceUrl: "https://www.dlnews.com/articles/defi/defi-developer-ameen-soleimani-back-with-new-stablecoin-hai/",
    sourceLabel: "DL News",
  },
  {
    name: "Lybra eUSD",
    symbol: "eUSD",
    logo: "eusd.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2024-06",
    peakMcap: 128_139_157,
    obituary:
      "Lybra Finance V2's LST-backed yield-bearing stablecoin peaked at $128M. After mining incentives ended in June 2024 and development stalled, supply collapsed. The protocol is technically live but abandoned by its team.",
    sourceUrl: "https://beincrypto.com/lybra-finance-lbr-defi-fall/",
    sourceLabel: "BeInCrypto",
  },
  {
    name: "Lybra peUSD",
    symbol: "peUSD",
    logo: "peusd.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2024-06",
    peakMcap: 43_983_623,
    obituary:
      "Lybra's omnichain version of eUSD, designed for cross-chain use. Died alongside eUSD V2 when the team abandoned the protocol.",
    sourceUrl: "https://beincrypto.com/lybra-finance-lbr-defi-fall/",
    sourceLabel: "BeInCrypto",
  },
  {
    name: "JPEG'd PUSd",
    symbol: "PUSD",
    logo: "pusd.jpg",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2024-06",
    peakMcap: 13_967_554,
    obituary:
      "JPEG'd's stablecoin minted against NFT collateral declined alongside the broader NFT market collapse. The protocol token stopped trading and the project was effectively abandoned.",
    sourceUrl: "https://defillama.com/protocol/jpegd",
    sourceLabel: "DefiLlama",
  },
  {
    name: "Hedge USD",
    symbol: "USH",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2024-06",
    peakMcap: 11_297_476,
    obituary:
      "Despite $3.7M in seed funding from Pantera and Solana Ventures, Hedge Protocol's stablecoin on Solana failed to gain traction in a competitive DeFi landscape. Supply dwindled from $11M to near zero.",
    sourceUrl: "https://defillama.com/stablecoin/hedge-usd",
    sourceLabel: "DefiLlama",
  },
  {
    name: "Preon STAR",
    symbol: "STAR",
    logo: "star.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2024-06",
    peakMcap: 32_136_242,
    obituary:
      "Preon Finance's stablecoin quietly died as the Sphere ecosystem faded. No shutdown announcement was made; supply simply declined from $32M to near zero.",
    sourceUrl: "https://defillama.com/protocol/preon-finance",
    sourceLabel: "DefiLlama",
  },
  {
    name: "Synthetix sEUR",
    symbol: "sEUR",
    logo: "seur.png",
    pegCurrency: "EUR",
    causeOfDeath: "abandoned",
    deathDate: "2024-07",
    peakMcap: 166_837_992,
    obituary:
      "Synthetix deprecated all non-USD spot synths on Ethereum mainnet as part of the V3 migration. sEUR holders who didn't swap in time could only redeem via the L1 redeemer contract at a discounted rate.",
    sourceUrl: "https://blog.synthetix.io/legacy-spot-synth-exchange-deprecation-migration/",
    sourceLabel: "Synthetix Blog",
  },
  {
    name: "UXD Stablecoin",
    symbol: "UXD",
    logo: "uxd.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2024-08",
    peakMcap: 41_817_136,
    obituary:
      "UXD Protocol's delta-neutral stablecoin on Solana survived the Mango Markets exploit but couldn't attract users. The team admitted the model \"isn't exciting enough for DeFi users\" and the DAO voted to sunset.",
    sourceUrl: "https://www.dlnews.com/articles/defi/solana-stablecoin-uxd-protocol-with-75m-usd-tvl-shuts-down/",
    sourceLabel: "DL News",
  },
  {
    name: "zkBob BOB",
    symbol: "BOB",
    logo: "bob.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2024-10",
    peakMcap: 16_000_251,
    obituary:
      "zkBob's privacy-focused stablecoin was deliberately sunset as the protocol switched to USDC, USDT, and ETH. The team noted BOB \"did not receive enough consumer usage to justify ongoing support.\"",
    sourceUrl: "https://blog.zkbob.com/tron-pool-closes-october-29-2024/",
    sourceLabel: "zkBob Blog",
  },
  {
    name: "Prisma mkUSD",
    symbol: "mkUSD",
    logo: "mkusd.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2024-11",
    peakMcap: 184_697_162,
    obituary:
      "After an $11.6M exploit in March 2024, Prisma Finance never recovered. Governance approved PIP-46 to decommission the protocol, reducing the debt ceiling to zero and introducing a PSM for orderly wind-down.",
    sourceUrl: "https://wavey.info/posts/2025/decomissioning-prisma-finance/",
    sourceLabel: "Wavey",
  },
  {
    name: "PrismaLRT ULTRA",
    symbol: "ULTRA",
    logo: "ultra.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2024-11",
    peakMcap: 22_649_284,
    obituary:
      "Prisma's LRT-backed stablecoin was decommissioned alongside mkUSD after the March 2024 exploit. A stability pool bug discovered during wind-down allowed one user to drain ~14 ETH.",
    sourceUrl: "https://wavey.info/posts/2025/decomissioning-prisma-finance/",
    sourceLabel: "Wavey",
  },
  {
    name: "Euro Tether",
    symbol: "EURT",
    logo: "eurt.png",
    pegCurrency: "EUR",
    causeOfDeath: "regulatory",
    deathDate: "2024-11",
    peakMcap: 324_057_865,
    obituary:
      "Peacefully retired by Tether as MiCA regulations made EU stablecoin issuance untenable. Holders given one year to redeem.",
    sourceUrl: "https://cointelegraph.com/news/tether-discontinues-euro-eurt-stablecoin",
    sourceLabel: "CoinTelegraph",
  },
  {
    name: "Overnight DAI+",
    symbol: "DAI+",
    logo: "dai-plus.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2024-12",
    peakMcap: 14_696_384,
    obituary:
      "Overnight Finance's yield-bearing DAI wrapper declined from $15M to near zero as the broader protocol wound down. CoinGecko reports circulating supply at zero.",
    sourceUrl: "https://defillama.com/stablecoin/dai+",
    sourceLabel: "DefiLlama",
  },
  {
    name: "Verified USD",
    symbol: "USDV",
    logo: "usdv.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2024-12",
    peakMcap: 26_330_184,
    obituary:
      "The Verified USD Foundation ceased support on December 31, 2024 and began removing all tokens from circulation. Backed by tokenized T-bills via Matrixport's STBT, the omnichain stablecoin never gained sufficient traction.",
    sourceUrl: "https://docs.usdv.money/docs",
    sourceLabel: "USDV Docs",
  },

  // ── 2025 ────────────────────────────────────────────────────────────
  {
    name: "Legacy BOLD",
    symbol: "BOLD",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2025-02",
    peakMcap: 34_600_000,
    obituary:
      "The first casualty of Liquity's own immutability principle. Legacy BOLD launched as the flagship of Liquity V2 — overcollateralized, decentralized, and permanently unchangeable. A Stability Pool vulnerability surfaced weeks after launch. The contracts couldn't be patched, so the team redeployed everything from scratch.",
    sourceUrl: "https://www.liquity.org/blog/liquity-v2-redeployment",
    sourceLabel: "Liquity Blog",
  },
  {
    name: "USD+",
    symbol: "USD+",
    logo: "usd-plus.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2025-01",
    peakMcap: 73_665_779,
    obituary:
      "Overnight Finance quietly wound down operations, leaving USD+ without active management or yield strategies.",
    sourceUrl: "https://overnight.fi/",
    sourceLabel: "Overnight.fi",
  },
  {
    name: "DYAD",
    symbol: "DYAD",
    logo: "dyad.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2025-06",
    peakMcap: 20_114_876,
    obituary:
      "DYAD's novel Kerosene-token model for overcollateralized CDPs failed to sustain interest. Supply declined from $20M peak to near zero despite continued GitHub activity.",
    sourceUrl: "https://defillama.com/stablecoin/dyad",
    sourceLabel: "DefiLlama",
  },
  {
    name: "Move Dollar",
    symbol: "MOD",
    logo: "mod.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2025-06",
    peakMcap: 19_484_463,
    obituary:
      "Thala Labs' stablecoin on Aptos declined from $19M to near zero. Despite a $25.5M exploit in Nov 2024 (funds recovered), MOD simply failed to compete as USDT/USDC expanded on Aptos.",
    sourceUrl: "https://www.coingecko.com/en/coins/move-dollar",
    sourceLabel: "CoinGecko",
  },
  {
    name: "GMO ZUSD",
    symbol: "ZUSD",
    logo: "zusd.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2025-06",
    peakMcap: 19_075_074,
    obituary:
      "GMO Trust's NYDFS-regulated stablecoin failed to gain market share despite expansions to Solana and Bitstamp listing. Supply dwindled to essentially zero while GMO's JPY stablecoin (GYEN) continues.",
    sourceUrl: "https://www.coingecko.com/en/coins/zusd",
    sourceLabel: "CoinGecko",
  },
  {
    name: "Gravita GRAI",
    symbol: "GRAI",
    logo: "grai.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2025-06",
    peakMcap: 15_428_881,
    obituary:
      "Gravita Protocol's interest-free borrowing model against LSTs failed to maintain adoption as competitors offered better terms. Supply dropped from $15M to near zero.",
    sourceUrl: "https://defillama.com/stablecoin/grai",
    sourceLabel: "DefiLlama",
  },
  {
    name: "High Yield USD",
    symbol: "HYUSD",
    logo: "hyusd.png",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2025-06",
    peakMcap: 11_268_731,
    obituary:
      "An RToken built on Reserve Protocol for yield-bearing exposure on Base. The Reserve platform thrives, but this individual RToken lost adoption as users moved to higher-yield alternatives.",
    sourceUrl: "https://defillama.com/stablecoin/high-yield-usd",
    sourceLabel: "DefiLlama",
  },
  {
    name: "JUST USDJ",
    symbol: "USDJ",
    logo: "usdj.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2025-08",
    peakMcap: 121_275_798,
    obituary:
      "TRON's legacy decentralized stablecoin was deliberately sunset as the ecosystem shifted to USDD. CDP functions ended August 2025, and 95% of supply was redeemed at a fixed rate of 1 USDJ = 1.5532 TRX.",
    sourceUrl: "https://en.cryptonomist.ch/2025/11/18/usdj-stablecoin-retirement-tron/",
    sourceLabel: "Cryptonomist",
  },
  {
    name: "Pinto",
    symbol: "PINTO",
    pegCurrency: "USD",
    causeOfDeath: "algorithmic-failure",
    deathDate: "2025-10",
    peakMcap: 13_100_000,
    obituary:
      "Beanstalk's first fork tried to give the credit-based stablecoin model a clean shot on Base, free from the governance exploit that killed the original. Without collateral backing and with insufficient demand for protocol debt, the price slid relentlessly from $1 to $0.11, proving the flaw was in the design, not the implementation.",
    sourceUrl: "https://www.coingecko.com/en/coins/pinto",
    sourceLabel: "CoinGecko",
  },
  {
    name: "Level USD",
    symbol: "LVLUSD",
    logo: "lvlusd.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2025-10",
    peakMcap: 185_007_045,
    obituary:
      "The Level team was acqui-hired by another DeFi protocol and announced the sunsetting of lvlUSD. Users could unstake and redeem with cooldown periods reduced to 2 seconds.",
    sourceUrl: "https://level-money.gitbook.io/level-documentation",
    sourceLabel: "Level Docs",
  },
  {
    name: "Lift Dollar",
    symbol: "USDL",
    logo: "usdl.png",
    pegCurrency: "USD",
    causeOfDeath: "abandoned",
    deathDate: "2025-10",
    peakMcap: 148_588_007,
    obituary:
      "Paxos wound down Lift Dollar to focus on larger-scale institutional products. Minting ended October 2025 and remaining USDL was converted to USDG (Paxos's new stablecoin).",
    sourceUrl: "https://www.paxos.com/newsroom/winding-down-usdl-lift-dollar",
    sourceLabel: "Paxos",
  },
  {
    name: "Coinshift csUSDL",
    symbol: "csUSDL",
    logo: "csusdl.png",
    pegCurrency: "USD",
    causeOfDeath: "counterparty-failure",
    deathDate: "2025-10",
    peakMcap: 142_014_760,
    obituary:
      "A yield-bearing wrapper around Paxos's USDL via Morpho Blue, killed by Paxos's decision to wind down USDL. Coinshift stopped accepting new deposits and raised borrow rates to close positions.",
    sourceUrl: "https://forum.morpho.org/t/notice-of-usdl-winddown/2062",
    sourceLabel: "Morpho Forum",
  },
  {
    name: "Elixir deUSD",
    symbol: "DEUSD",
    logo: "deusd.png",
    pegCurrency: "USD",
    causeOfDeath: "counterparty-failure",
    deathDate: "2025-11",
    peakMcap: 301_727_222,
    obituary:
      "Lost 97% of value overnight when counterparty Stream Finance disclosed a $93M loss, wiping out 65% of deUSD's collateral.",
    sourceUrl: "https://beincrypto.com/elixir-deusd-stablecoin-collapse-stream-finance-loss/",
    sourceLabel: "BeInCrypto",
  },
  {
    name: "Reservoir rUSD",
    symbol: "rUSD",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2025-12",
    peakMcap: 88_500_000,
    obituary:
      "Reservoir boasted about processing $285M in redemptions during November 2025 'without failure' — technically true, but the patient survived the surgery only to flatline. Supply dropped from $88M to under $700K as every dollar that could leave, did.",
    sourceUrl: "https://defillama.com/stablecoin/reservoir-stablecoin",
    sourceLabel: "DefiLlama",
  },

  // ── 2026 ────────────────────────────────────────────────────────────
  {
    name: "Palm USD",
    symbol: "PUSD",
    pegCurrency: "USD",
    causeOfDeath: "liquidity-drain",
    deathDate: "2026-01",
    peakMcap: 26_000_000,
    obituary:
      "Palm USD promised to bridge Islamic finance and crypto with a Shariah-compliant, un-freezeable stablecoin backed by Gulf currencies. Despite announcing a $2.8B purchase agreement, actual circulating supply briefly touched $26M before collapsing to $81K. The billions sit perpetually 'unreleased.'",
    sourceUrl: "https://www.theblock.co/press-releases/378989/palm-usd-launches-pusd-a-global-free-stablecoin-backed-by-aed-and-sar",
    sourceLabel: "The Block",
  },
];
