import type { StablecoinMeta, PegCurrency } from "./types";

/**
 * Extended stablecoin registry: the full DefiLlama universe beyond the
 * hand-curated core list in stablecoins.ts (added 2026-07, Pharos-parity).
 *
 * Classification provenance: pegCurrency and backing derive mechanically from
 * DefiLlama pegType/pegMechanism; governance tiers were batch-classified
 * (AI-assisted, reviewed) using the same three-tier system as the core list.
 * Entries here carry no collateral/redemption prose. Promote a coin to
 * stablecoins.ts when it deserves full hand-curated metadata.
 */

interface ExtOpts {
  yieldBearing?: boolean;
  navToken?: boolean;
  rwa?: boolean;
}

function x(
  id: string,
  name: string,
  symbol: string,
  backing: StablecoinMeta["flags"]["backing"],
  pegCurrency: PegCurrency,
  governance: StablecoinMeta["flags"]["governance"],
  opts?: ExtOpts,
): StablecoinMeta {
  return {
    id,
    name,
    symbol,
    flags: {
      backing,
      pegCurrency,
      governance,
      yieldBearing: opts?.yieldBearing ?? false,
      rwa: opts?.rwa ?? false,
      navToken: opts?.navToken ?? false,
    },
  };
}

export const EXTENDED_STABLECOINS: StablecoinMeta[] = [
  x("214", "USDX Money USDX", "USDX", "crypto-backed", "USD", "centralized-dependent"),
  x("258", "A7A5", "A7A5", "rwa-backed", "RUB", "centralized", { yieldBearing: true, rwa: true }),
  x("406", "Polymarket USD", "pUSD", "crypto-backed", "USD", "centralized"),
  x("153", "Binance Peg BUSD", "BUSD", "crypto-backed", "USD", "centralized", { rwa: true }),
  x("17", "HUSD", "HUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("21", "flexUSD", "FLEXUSD", "crypto-backed", "USD", "centralized", { yieldBearing: true }),
  x("328", "Mustang Finance", "MUST", "crypto-backed", "USD", "decentralized"),
  x("400", "Saturn Dollar", "USDAT", "crypto-backed", "USD", "centralized", { rwa: true }),
  x("389", "CFX MoveUSD", "MOVEUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("398", "Valtorum USD", "USDV", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("407", "Unity USD", "UUSD", "crypto-backed", "USD", "centralized"),
  x("405", "AP USDA", "USDA", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("373", "Sui Dollar", "USDSUI", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("22", "sUSD", "SUSD", "crypto-backed", "USD", "decentralized"),
  x("408", "Ondo U.S. Dollar Token", "USDon", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("97", "USP Stablecoin", "USP", "crypto-backed", "USD", "centralized-dependent"),
  x("427", "JPYSC", "JPYSC", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("401", "Tori trUSD", "trUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("409", "USDKG", "USDKG", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("226", "Frankencoin", "ZCHF", "crypto-backed", "CHF", "decentralized"),
  x("4", "Binance USD", "BUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("317", "Tokenised GBP", "tGBP", "rwa-backed", "GBP", "centralized", { rwa: true }),
  x("67", "Bean", "BEAN", "algorithmic", "USD", "decentralized"),
  x("410", "Universal USD", "USDU", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("297", "Main Street USD", "MSUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("413", "SoulPeg USD", "SPUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("385", "PathUSD", "pathUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("365", "BRLA Digital", "BRLA", "rwa-backed", "BRL", "centralized", { rwa: true }),
  x("44", "dForce USD", "USX", "crypto-backed", "USD", "centralized-dependent"),
  x("85", "Real USD", "USDR", "algorithmic", "USD", "centralized-dependent", { yieldBearing: true, rwa: true }),
  x("31", "SpiceUSD", "USDS", "algorithmic", "USD", "centralized-dependent"),
  x("414", "Royal Euro", "REUR", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("29", "TOR", "TOR", "crypto-backed", "USD", "centralized-dependent"),
  x("327", "Mu Digital AZND", "AZND", "crypto-backed", "USD", "centralized-dependent"),
  x("355", "JPY Coin", "JPYC", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("215", "Moneta", "USDM", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("247", "Schuman EUROP", "EUROP", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("417", "Defi.money", "MONEY", "crypto-backed", "USD", "decentralized"),
  x("376", "eSui Dollar", "suiUSDe", "crypto-backed", "USD", "centralized-dependent"),
  x("289", "XSGD", "XSGD", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("13", "YUSD Stablecoin", "YUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("312", "Hydrated Dollar", "HOLLAR", "crypto-backed", "USD", "centralized-dependent"),
  x("411", "Stable Mint USD", "USDSM", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("165", "AUDD", "AUDD", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("115", "R", "R", "crypto-backed", "USD", "decentralized"),
  x("308", "Saga Dollar", "D", "crypto-backed", "USD", "centralized-dependent"),
  x("416", "Telcoin eUSD", "eUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("274", "Quantoz EURQ", "EURQ", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("42", "USDX", "USDX", "crypto-backed", "USD", "centralized-dependent"),
  x("244", "Lift Dollar", "USDL", "rwa-backed", "USD", "centralized", { yieldBearing: true, rwa: true }),
  x("415", "Royal Dollar", "RUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("324", "Stable Coin", "SBC", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("51", "Stasis Euro", "EURS", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("234", "Worldwide USD", "WUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("331", "USP", "USP", "crypto-backed", "USD", "centralized-dependent", { rwa: true }),
  x("103", "NXUSD", "NXUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("350", "Citrea USD", "ctUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("253", "USBD", "USBD", "crypto-backed", "USD", "centralized-dependent"),
  x("66", "Frax Price Index", "FPI", "algorithmic", "VAR", "centralized-dependent", { navToken: true }),
  x("386", "Western Union USDPT", "USDPT", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("12", "Neutrino USD", "USDN", "algorithmic", "USD", "centralized-dependent"),
  x("122", "GYEN", "GYEN", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("300", "Bilira", "TRYB", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("418", "Cod3x USD", "cdxUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("23", "Origin Dollar", "OUSD", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("60", "HomeCoin", "HOME", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true, rwa: true }),
  x("183", "Bitcoin USD", "BtcUSD", "crypto-backed", "USD", "decentralized"),
  x("75", "Youves uUSD", "UUSD", "crypto-backed", "USD", "decentralized"),
  x("391", "USDST", "USDST", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("266", "Plume USD", "pUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("379", "Argentine Peso", "WARS", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("89", "XAI", "XAI", "crypto-backed", "USD", "centralized-dependent"),
  x("420", "Startale USD", "USDSC", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("178", "Web 3 Dollar", "USD3", "crypto-backed", "USD", "centralized-dependent"),
  x("245", "Anzens USDA", "USDA", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("16", "Parrot USD", "PAI", "crypto-backed", "USD", "centralized-dependent"),
  x("421", "Flying Tulip USD", "ftUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("9", "Fei USD", "FEI", "algorithmic", "USD", "decentralized"),
  x("299", "PHT Stablecoin", "PHT", "crypto-backed", "OTHER", "centralized-dependent"),
  x("422", "Forte AUD", "AUDF", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("314", "Palm USD", "PUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("26", "mStable USD", "MUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("280", "Tether CNH", "CNHT", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("70", "DigitalDollar", "DUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("30", "Dollar on Chain", "DOC", "crypto-backed", "USD", "decentralized"),
  x("388", "Initia iUSD", "iUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("157", "VNX Swiss Franc", "VCHF", "rwa-backed", "CHF", "centralized", { rwa: true }),
  x("404", "Monetrix USDM", "USDM", "crypto-backed", "USD", "centralized-dependent"),
  x("33", "USDP Stablecoin", "USDP", "crypto-backed", "USD", "centralized-dependent"),
  x("377", "Nerona USD", "USDnr", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("186", "International Stable Currency", "ISC", "rwa-backed", "VAR", "centralized", { yieldBearing: true, navToken: true, rwa: true }),
  x("159", "RIF US Dollar", "USDRIF", "crypto-backed", "USD", "decentralized"),
  x("18", "Nexus USD", "NUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("356", "US Sonic Dollar", "USSD", "crypto-backed", "USD", "centralized-dependent"),
  x("93", "Djed StableCoin", "DJED", "algorithmic", "USD", "decentralized"),
  x("351", "Tetris Money", "RUBT", "rwa-backed", "RUB", "centralized", { rwa: true }),
  x("236", "Synnax Stablecoin", "syUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("242", "Hermetica USDh", "USDH", "rwa-backed", "USD", "centralized-dependent"),
  x("240", "StablR USD", "USDR", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("291", "Parallel USDp", "USDp", "crypto-backed", "USD", "centralized-dependent"),
  x("162", "XUSD", "XUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("28", "Vai", "VAI", "crypto-backed", "USD", "centralized-dependent"),
  x("423", "Decentralized Euro", "dEURO", "crypto-backed", "EUR", "decentralized"),
  x("55", "EURA", "EURA", "crypto-backed", "EUR", "centralized-dependent", { rwa: true }),
  x("160", "Sovryn Dollar", "DLLR", "crypto-backed", "USD", "decentralized"),
  x("397", "Hyperbeat USD", "beatUSD", "rwa-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("52", "Mento Euro", "EURm", "algorithmic", "EUR", "centralized-dependent"),
  x("145", "CAD Coin", "CADC", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("378", "USD Somnia", "USDso", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("426", "Streamflow USD+", "USD+", "rwa-backed", "USD", "centralized", { yieldBearing: true, rwa: true }),
  x("425", "The Fedz FUSD", "FUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("76", "Interest Protocol", "USDI", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("261", "Solomon USDv", "USDV", "crypto-backed", "USD", "centralized-dependent"),
  x("88", "iUSD", "IUSD", "crypto-backed", "USD", "decentralized"),
  x("83", "USDW", "USDW", "crypto-backed", "USD", "centralized-dependent"),
  x("54", "USN", "USN", "algorithmic", "USD", "centralized-dependent"),
  x("224", "dTRINITY USD", "dUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("113", "SILK", "SILK", "crypto-backed", "VAR", "centralized-dependent", { navToken: true }),
  x("132", "USDM", "USDM", "rwa-backed", "USD", "centralized", { yieldBearing: true, rwa: true }),
  x("334", "Macropod", "AUDM", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("152", "Liquid Loans USDL", "USDL", "crypto-backed", "USD", "decentralized"),
  x("56", "Parallel", "PAR", "crypto-backed", "EUR", "centralized-dependent"),
  x("78", "Note", "NOTE", "crypto-backed", "USD", "centralized-dependent"),
  x("151", "zkUSD Dollar", "zkUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("424", "Stablecorp QCAD", "QCAD", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("40", "Rai Reflex Index", "RAI", "crypto-backed", "VAR", "decentralized", { navToken: true }),
  x("53", "sEUR", "SEUR", "crypto-backed", "EUR", "decentralized"),
  x("155", "Glo Dollar", "USDGLO", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("65", "USDH", "USDH", "crypto-backed", "USD", "centralized-dependent"),
  x("281", "Mexican Peso Tether", "MXNT", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("319", "AllUnity EUR", "EURAU", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("158", "VNX EURO", "VEUR", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("268", "YU", "YU", "crypto-backed", "USD", "centralized-dependent"),
  x("216", "Solayer USD", "sUSD", "rwa-backed", "USD", "centralized-dependent", { yieldBearing: true, rwa: true }),
  x("390", "FinChain Dollar", "FUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("392", "Newrails Euro", "EURW", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("107", "Czodiac USD", "CZUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("92", "Meme Dollar", "PINA", "algorithmic", "USD", "centralized-dependent"),
  x("366", "Alto DUSD", "DUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("380", "Brazilian Real", "WBRL", "rwa-backed", "BRL", "centralized", { rwa: true }),
  x("192", "Angle USDA", "USDA", "crypto-backed", "USD", "centralized-dependent", { rwa: true }),
  x("204", "Balanced Dollars", "BNUSD", "crypto-backed", "USD", "decentralized"),
  x("387", "CAD Digital", "CADD", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("349", "Pareto USP", "USP", "crypto-backed", "USD", "centralized-dependent", { rwa: true }),
  x("428", "KRWQ", "KRWQ", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("43", "ZUSD", "ZUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("238", "Rings scUSD", "SCUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("81", "USK", "USK", "crypto-backed", "USD", "centralized-dependent"),
  x("176", "Fathom Dollar", "FXD", "crypto-backed", "USD", "centralized-dependent"),
  x("41", "Float Protocol Float", "FLOAT", "algorithmic", "VAR", "decentralized", { navToken: true }),
  x("277", "SMARDEX USDN", "USDN", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("125", "eUSD (V2)", "eUSD(v2)", "crypto-backed", "USD", "decentralized", { yieldBearing: true }),
  x("399", "Agant GBP", "GBPA", "rwa-backed", "GBP", "centralized", { rwa: true }),
  x("46", "Overnight USD+", "USD+", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("175", "PXDC Stablecoin", "PXDC", "crypto-backed", "USD", "centralized-dependent"),
  x("167", "Fractional ETH", "fETH", "crypto-backed", "VAR", "decentralized", { navToken: true }),
  x("211", "Threshold USD", "THUSD", "crypto-backed", "USD", "decentralized"),
  x("285", "Good Game US Dollar", "GGUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("419", "Elara USD", "elUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("229", "Level USD", "LVLUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("32", "Sperax USD", "USDS", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("72", "Kolibri USD", "KUSD", "crypto-backed", "USD", "decentralized"),
  x("278", "WEUSD", "WEUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("27", "USDK", "USDK", "rwa-backed", "USD", "centralized"),
  x("143", "Verified USD", "USDV", "rwa-backed", "USD", "centralized-dependent", { rwa: true }),
  x("58", "3USD", "3USD", "crypto-backed", "USD", "centralized-dependent"),
  x("171", "Lets Get HAI", "HAI", "crypto-backed", "USD", "decentralized"),
  x("198", "Stable Jack aUSD", "aUSD", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("333", "mantraUSD", "mantraUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("180", "Bread", "BREAD", "crypto-backed", "USD", "centralized-dependent"),
  x("293", "Sigma Money bnbUSD", "BNBUSD", "crypto-backed", "USD", "decentralized"),
  x("179", "CJPY", "CJPY", "crypto-backed", "OTHER", "decentralized"),
  x("358", "Mento British Pound", "GBPm", "crypto-backed", "GBP", "centralized-dependent"),
  x("206", "Opus CASH", "CASH", "crypto-backed", "USD", "decentralized"),
  x("217", "Reservoir Stablecoin", "rUSD", "rwa-backed", "USD", "centralized-dependent", { rwa: true }),
  x("181", "Zunami USD", "zunUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("64", "UXD Stablecoin", "UXD", "algorithmic", "USD", "centralized-dependent"),
  x("295", "Asymmetry USDaf V2", "USDaf", "crypto-backed", "USD", "centralized-dependent"),
  x("174", "rUSD", "rUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("191", "bitSmiley USD", "bitUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("126", "mkUSD", "mkUSD", "crypto-backed", "USD", "decentralized"),
  x("116", "GRAI", "GRAI", "crypto-backed", "USD", "decentralized"),
  x("112", "USDT+", "USDT+", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("48", "BAI Stablecoin", "BAI", "crypto-backed", "USD", "centralized-dependent"),
  x("49", "Euro Tether", "EURT", "rwa-backed", "EUR", "centralized"),
  x("164", "USDCB", "USDCB", "rwa-backed", "USD", "centralized"),
  x("135", "Inter Stable Token", "IST", "crypto-backed", "USD", "centralized-dependent"),
  x("199", "Mento Real", "BRLm", "crypto-backed", "BRL", "centralized-dependent"),
  x("227", "Legacy BOLD", "BOLD", "crypto-backed", "USD", "decentralized"),
  x("73", "USDtez", "USDTZ", "rwa-backed", "USD", "centralized"),
  x("25", "Reserve", "RSV", "crypto-backed", "USD", "centralized-dependent"),
  x("38", "STBL", "STBL", "crypto-backed", "USD", "centralized-dependent"),
  x("412", "MYR Stablecoin", "MYRT", "rwa-backed", "OTHER", "centralized"),
  x("59", "SigmaUSD", "SIGUSD", "algorithmic", "USD", "decentralized"),
  x("311", "iAUSD", "IAUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("68", "USDLemma", "USDL", "algorithmic", "USD", "centralized-dependent"),
  x("130", "Savvy USD", "SVUSD", "rwa-backed", "USD", "centralized-dependent"),
  x("292", "VNX British Pound", "VGBP", "rwa-backed", "GBP", "centralized"),
  x("367", "Mento Kenyan Shilling", "KESm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("248", "USDFC", "USDFC", "crypto-backed", "USD", "decentralized"),
  x("322", "Last USD", "USDXL", "crypto-backed", "USD", "centralized-dependent"),
  x("34", "USD Balance", "USDB", "algorithmic", "USD", "centralized-dependent"),
  x("228", "Quill USD", "USDQ", "crypto-backed", "USD", "decentralized"),
  x("104", "Davos Protocol", "DUSD", "crypto-backed", "USD", "decentralized"),
  x("337", "USE", "USE", "algorithmic", "USD", "centralized-dependent"),
  x("363", "Mento Japanese Yen", "JPYm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("98", "EUROe Stablecoin", "EUROe", "rwa-backed", "EUR", "centralized"),
  x("370", "Mento Swiss Franc", "CHFm", "crypto-backed", "CHF", "centralized-dependent"),
  x("144", "High Yield USD", "HYUSD", "algorithmic", "USD", "centralized-dependent", { yieldBearing: true }),
  x("45", "aUSD Seed", "aSEED", "crypto-backed", "USD", "decentralized"),
  x("359", "Mento Philippine Peso", "PHPm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("124", "peg-eUSD", "peUSD", "crypto-backed", "USD", "decentralized"),
  x("188", "Orby USC", "USC", "crypto-backed", "USD", "centralized-dependent"),
  x("233", "TheStandard USD", "USDS", "crypto-backed", "USD", "centralized-dependent"),
  x("361", "Mento Australian Dollar", "AUDm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("149", "Sable Coin", "USDS", "crypto-backed", "USD", "decentralized"),
  x("109", "eUSD", "EUSD", "crypto-backed", "USD", "decentralized", { yieldBearing: true }),
  x("394", "invUSD Stablecoin", "invUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("37", "USDJ", "USDJ", "crypto-backed", "USD", "centralized-dependent"),
  x("382", "Colombian Peso", "WCOP", "rwa-backed", "OTHER", "centralized"),
  x("184", "Magma Wen", "WEN", "crypto-backed", "USD", "centralized-dependent"),
  x("200", "Hedera Swiss Franc", "HCHF", "crypto-backed", "CHF", "decentralized"),
  x("142", "HYDT", "HYDT", "algorithmic", "USD", "centralized-dependent"),
  x("82", "arUSD", "ARUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("39", "VOLT Protocol", "VOLT", "algorithmic", "VAR", "centralized-dependent", { yieldBearing: true, navToken: true }),
  x("71", "Vesta Stable", "VST", "crypto-backed", "USD", "centralized-dependent"),
  x("374", "Phoenix USD", "phUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("99", "Stabl.fi Cash", "CASH", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("381", "Chilean Peso", "WCLP", "rwa-backed", "OTHER", "centralized"),
  x("148", "Mynth MyUSD", "MyUSD", "algorithmic", "USD", "centralized-dependent"),
  x("123", "STAR", "STAR", "crypto-backed", "USD", "centralized-dependent"),
  x("362", "Mento Colombian Peso", "COPm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("369", "Mento Nigerian Naira", "NGNm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("201", "HEX Dollar Coin", "HEXDC", "crypto-backed", "USD", "decentralized"),
  x("304", "USDU Finance", "USDU", "crypto-backed", "USD", "centralized-dependent"),
  x("383", "Mexican Peso", "WMXN", "rwa-backed", "OTHER", "centralized"),
  x("260", "VDollar Finance", "VUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("105", "DeFi Franc", "DCHF", "crypto-backed", "VAR", "decentralized", { navToken: true }),
  x("243", "Coinshift", "csUSDL", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true, navToken: true, rwa: true }),
  x("117", "Ethos Reserve Note", "ERN", "crypto-backed", "USD", "centralized-dependent"),
  x("287", "Nerite USND", "USND", "crypto-backed", "USD", "decentralized"),
  x("264", "XBANKING USDE", "USDE", "crypto-backed", "USD", "centralized-dependent"),
  x("294", "NonDollar", "USDA+", "crypto-backed", "USD", "centralized-dependent"),
  x("368", "Mento South African Rand", "ZARm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("357", "Bytecash", "BYC", "crypto-backed", "USD", "centralized-dependent"),
  x("90", "Redeemable USD", "RUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("57", "Hedge USD", "USH", "crypto-backed", "USD", "decentralized"),
  x("384", "Peruvian Sol", "WPEN", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("212", "Move Dollar", "MOD", "crypto-backed", "USD", "centralized-dependent"),
  x("96", "Coin98 Dollar", "CUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("364", "Whale Asset Dollar", "WAD", "crypto-backed", "USD", "centralized-dependent"),
  x("371", "Mento West African CFA Franc", "XOFm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("207", "Dyad", "DYAD", "crypto-backed", "USD", "decentralized"),
  x("276", "Hyperstable USD", "USH", "crypto-backed", "USD", "decentralized"),
  x("114", "CLever USD", "clevUSD", "crypto-backed", "USD", "decentralized"),
  x("138", "ARYZE eUSD", "eUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("288", "EBUSD", "EBUSD", "crypto-backed", "USD", "decentralized"),
  x("94", "BaoUSD", "BAOUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("372", "Mento Ghanaian Cedi", "GHSm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("170", "EURO3", "EURO3", "crypto-backed", "EUR", "centralized-dependent"),
  x("100", "Digital Standard Unit", "DSU", "crypto-backed", "USD", "centralized-dependent"),
  x("84", "BOB", "BOB", "crypto-backed", "USD", "centralized-dependent"),
  x("360", "Mento Canadian Dollar", "CADm", "crypto-backed", "OTHER", "centralized-dependent"),
  x("222", "Parallel USD", "PAUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("139", "ARYZE eEUR", "eEUR", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("111", "DAI+", "DAI+", "crypto-backed", "USD", "centralized-dependent", { yieldBearing: true }),
  x("74", "Moremoney USD", "MONEY", "crypto-backed", "USD", "centralized-dependent"),
  x("177", "UNO", "UNO", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("169", "GAI Stablecoin", "GAI", "crypto-backed", "USD", "centralized-dependent"),
  x("196", "Classic USD", "USC", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("189", "btcUSD", "btcUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("163", "PrismaLRT Ultra", "ULTRA", "crypto-backed", "USD", "decentralized"),
  x("267", "Mead", "MEAD", "crypto-backed", "USD", "centralized-dependent"),
  x("323", "KEI Stablecoin", "KEI", "crypto-backed", "USD", "centralized-dependent"),
  x("91", "Iron Bank EURO", "IBEUR", "crypto-backed", "EUR", "centralized-dependent"),
  x("208", "Dackie USD", "DCKUSD", "algorithmic", "USD", "centralized-dependent"),
  x("190", "Revenue Generating USD", "rgUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("259", "Arche Protocol MSD", "MSD", "crypto-backed", "USD", "centralized-dependent"),
  x("102", "Offshift anonUSD", "ANONUSD", "algorithmic", "USD", "centralized-dependent"),
  x("140", "ARYZE eGBP", "eGBP", "rwa-backed", "GBP", "centralized", { rwa: true }),
  x("338", "Fuse Dollar V3", "FUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("108", "Deuterium", "d2O", "crypto-backed", "USD", "centralized-dependent"),
  x("137", "Collateralized Debt Token", "CDT", "crypto-backed", "VAR", "centralized-dependent", { navToken: true }),
  x("61", "Fixed Income Asset Token", "FIAT", "crypto-backed", "USD", "centralized-dependent"),
  x("193", "Chi USC", "USC", "crypto-backed", "USD", "decentralized"),
  x("62", "PUSd", "PUSD", "crypto-backed", "USD", "decentralized"),
  x("301", "Jigsaw USD", "JUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("393", "Harbor haEUR", "haEUR", "crypto-backed", "EUR", "centralized-dependent"),
  x("396", "Deaderal Reserve Note", "USDeAD", "crypto-backed", "USD", "centralized-dependent"),
  x("128", "Nexus", "NEX", "algorithmic", "USD", "centralized-dependent"),
  x("223", "TREN Debt Token", "XY", "crypto-backed", "USD", "centralized-dependent"),
  x("87", "USDi", "USDI", "crypto-backed", "USD", "centralized-dependent"),
  x("127", "Alternity CNY", "LCNY", "crypto-backed", "OTHER", "centralized-dependent"),
  x("187", "KNOX Dollar", "KNOX", "crypto-backed", "USD", "centralized-dependent"),
  x("131", "UAHT", "UAHT", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("273", "Asymmetry USDaf", "USDaf", "crypto-backed", "USD", "centralized-dependent"),
  x("403", "Money Protocol", "BPD", "crypto-backed", "USD", "decentralized"),
  x("265", "Orki USD", "USDK", "crypto-backed", "USD", "decentralized"),
  x("161", "Quantoz EURD", "EURD", "rwa-backed", "EUR", "centralized", { rwa: true }),
  x("279", "Parabol USD", "paraUSD", "rwa-backed", "USD", "centralized", { yieldBearing: true, rwa: true }),
  x("133", "NARS", "NARS", "rwa-backed", "OTHER", "centralized", { rwa: true }),
  x("330", "Gaming XP USD", "xpUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("402", "Kerne USD", "kUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("345", "Uncap USD", "USDU", "crypto-backed", "USD", "centralized-dependent"),
  x("150", "USD Stable Colb", "SCB", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("352", "BRTH", "BRTH", "rwa-backed", "BRL", "centralized", { rwa: true }),
  x("318", "litUSD", "litUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("121", "PSY", "sLSD", "crypto-backed", "USD", "centralized-dependent"),
  x("182", "Zunami ETH", "zunETH", "crypto-backed", "VAR", "decentralized", { navToken: true }),
  x("134", "Phase Dollar", "CASH", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("203", "Chad USD", "cUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("395", "fUSD", "FUSD", "rwa-backed", "USD", "centralized", { rwa: true }),
  x("320", "Rocky USDr", "USDR", "crypto-backed", "USD", "centralized-dependent"),
  x("375", "Monet USDmo", "USDMO", "crypto-backed", "USD", "centralized-dependent"),
  x("210", "Elixir deUSD", "DEUSD", "crypto-backed", "USD", "centralized-dependent"),
  x("3", "TerraClassicUSD", "USTC", "algorithmic", "USD", "decentralized"),
];
